### ISSUE TITLE
Move to todotxt organization

### ISSUE THREAD

**Issue by evanp** [todotxt/language-todotxt#18]
There's a new organization managing the todotxt/todo.txt-cli and other apps. It'd be great to move this repo there and get more group maintenance.

It's better to move it than fork it since the issues will all move along with it. 

@karbassi manages the organization and could help with the move. I would be happy to help maintain the codebase after the move.

@gerane we would also need to figure out how to manage the push to the Atom package manager.

**Comment by gerane** [comment]
@evenp @karbassi I think this would be the best idea. I originally ported this from a sublime extension, and I am not that skilled at js\cofeescript. I am a systems engineer and spend the majority of my time using PowerShell, so a couple years ago I migrated to visual studio code when it released for the better PowerShell experience.

I would even be willing to transfer ownership if anyone would like to take it over entirely. It is very hard to maintain for me since I no longer use atom.

**Comment by karbassi** [comment]
@gerane Yes, this would be great to move under the org.

Before a transfer, you'd have to relicense this under GPLv3. Will that be okay?

**Comment by evanp** [comment]
@karbassi since the BSD license is compatible with the GPLv3, we can just relicense the package after it's moved. All the existing code is compatible with the GPLv3.

**Comment by evanp** [comment]
@gerane also, you'd need to figure out how to share whatever credentials are used to push to the atom package manager. I haven't done that before, so I don't know the scoop, but it'd be nice if people who had the current version could get upgrades automatically.

**Comment by evanp** [comment]
@gerane @karbassi Are we good to go? Can we get this done?

**Comment by karbassi** [comment]
We're good. I've added him to the ORG as a member. Waiting for @gerane to accept and start the transfer.

**Comment by evanp** [comment]
Sweet! @gerane can you get that going? @karbassi can you add me as a member, and give me access to the repo once @gerane has made the transfer?

**Comment by karbassi** [comment]
@evanp done.

**Comment by evanp** [comment]
So now we're just waiting for @gerane to move the repository, correct?

**Comment by gerane** [comment]
Sorry for the delay. @karbassi @evanp  I have had very little keyboard free time. I was wanting to make sure I did the transfer properly. Is the organization name "todotxt" or "todo.txt" for the purpose of the transfer?

**Comment by gerane** [comment]
@evanp @karbassi Ok, done. I also was looking into the atom package manager end, and it looks like all that needs to be done is edit the package.json repository information and then you can also publish to atom's package repository as well. 

http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/

**Comment by karbassi** [comment]
Closing this since the main task is done. The package manager url task is at #22.
