### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by karbassi** [todotxt/language-todotxt#23]
The README needs:

- [ ] todo.txt logo
- [ ] link to todotxt.org
- [ ] link to LICENSE
- [ ] link to CODE_OF_CONDUCT

**Comment by evanp** [comment]
@karbassi Can you give me a link to the logo?

**Comment by karbassi** [comment]
@evanp This is the highest res I have seen. https://github.com/todotxt/todotxt.github.io/blob/master/images/todotxt_logo_2012.png

@ginatrapani is there larger versions somewhere in your possession? Maybe a vector version or Photoshop file?

**Comment by evanp** [comment]
I'm going to make the logo a separate issue
