### ISSUE TITLE
don't understand

### ISSUE THREAD

**Issue by dcrystalj** [todotxt/language-todotxt#5]
Can you provide a example of usage? I have no idea how to use this. Its nothing colored.

**Comment by atwupack** [comment]
Hello,

maybe this can help you: http://todotxt.com/
The format of the file can be found here: https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format

André

**Comment by evanp** [comment]
This package currently colorizes todo.txt files. Closing this issue.

**Comment by mn113** [comment]
OP has a valid point. This project is overly cryptic. Its README would be enhanced if it included a few basic usage examples, instead of expecting every new visitor to click through to todotxt.org to learn the syntax.
