### ISSUE TITLE
Adding commands from tmTodoTXT, with keyboard shortcuts

### ISSUE THREAD

**Issue by the-solipsist** [todotxt/language-todotxt#6]
Would you consider adding commands like these as well, as a complement to syntax highlighting? https://github.com/sideshowcoder/tmTodoTXT/tree/master/Commands

**Comment by evanp** [comment]
OK, I've looked over the list of commands there, and there's now an issue for each one:

- Archive Done Tasks = #10 
- Create like current = #30 
- Set task date = #31 
- Set task done = #12 

I'm going to track the functionality for each of those issues and close this one.
